"""Add downvote column

Revision ID: f374d23cbbbe
Revises: afd2e278bd1a
Create Date: 2023-12-08 00:00:42.641858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f374d23cbbbe'
down_revision = 'afd2e278bd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downvote', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('downvote')

    # ### end Alembic commands ###
